config/routes.rb
Rails.application.routes.draw do
  get "log_in", to: "sessions#new", as: "log_in"
  get "log_out", to: "sessions#destroy", as: "log_out"

  get "sign_up", to: "users#new", as: "sign_up"

  root to: "users#new"

  resources :users
  resources :sessions

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  before_save :encrypt_password

  validates :password,
    confirmation: true
  validates :password,
    presence: true, on: :create

  validates :email,
    presence: true,
    uniqueness: true

  class << self
    def authenticate(email, password)
      user = where(email: email).first

      if user && user.encrypted_password ==
        BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user


  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(
      session_params[:email],
      session_params[:password]
    )

    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end


  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: %i[:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url, notice: "Signed Up!"
    else
      render "new"
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Auth
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - flash.each do |name, messages|
      .flash(id="flash#{name}")
        = messages

    .user-nav
      - if current_user
        Logged in as #{ current_user.email }
      - else
        = link_to "Sign up", sign_up_path
        &nbsp; or &nbsp;
        = link_to "Log in", log_in_path

    = yield

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/users/new.html.haml
%h1 Sign Up

= render 'form'